### PR TITLE
ignore test artifacts

### PR DESCRIPTION
**Pull request by djmitche**
These were popping up after I ran 'npm test'.

### CODE REVIEW

**Comment by djmitche** [comment]
@jhford I can't assign this to you for some reason, but please review

**Comment by jhford** [comment]
we can't ignore lib/ because the default action of npm is to reuse the gitignore file to ignore its own files.  Because of that, we wouldn't package up the babel output and the resulting code we'd be publishing would be junk.

We could probably put .test in there, but lib/ cannot be put in there.

**Comment by jhford** [comment]
unless you know how to do some sort of #include for .gitignore and .npmignore

**Comment by jhford** [comment]
we want to not git add lib or .test but we don't want them in .gitignore.  We could have two files, but keeping them in sync is a lot of hassle.

**Comment by djmitche** [comment]
Could we add `.test` to both `.gitignore` and `.npmignore` and `lib` to just `.gitignore`?  I don't see these changing too often, so not that much hassle.  Or maybe I'm missing something?

**Comment by jhford** [comment]
we don't have .npmignores in any other projects that I'm aware of.  I'd rather us not start doing this for this repo when we don't do it in any other repository.

**Comment by djmitche** [comment]
OK -- I'll just add it to .git/info/exclude

**Pull request closed without merging**
