### PR TITLE
404 Error handler

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Fixes [bugzilla#1421330](https://bugzilla.mozilla.org/show_bug.cgi?id=1421330)

### CODE REVIEW

**Review by djmitche — CHANGES_REQUESTED** [review]
(sorry for the delay!!)

This looks good, but I'd like to see a test to make sure that it's working.  Once that's in place we can release this library and try using it in a service.

**Review by djmitche — APPROVED** [review]
Nice work!

**Comment by djmitche** [comment]
This will be released as v10.2.0 shortly.

I modified the test a little in https://github.com/taskcluster/taskcluster-lib-app/commit/a38a7fba140aedcd16e880a6af13aeff392387bc:
 * check the Content-Security-Policy header (since that's what the bug was about, originally)
 * handle the Promise from `request.get`, and fail if no exception is raised

Do you want to try updating, say, github.com/taskcluster/taskcluster-secrets so that we can make sure this works "in real life"?

**Comment by arshadkazmi42** [comment]
Yes. I would love to work on that. Is there a bug created for it with details on the fix needs to be done?

**Comment by djmitche** [comment]
Let's do so using the same bug (1421330).  All that needs to be done is to update the version of tc-lib-app in the taskcluster-secrets repo and verify that the tests still pass.  Once it's deployed, we can double-check the response for a 404.

**Comment by arshadkazmi42** [comment]
I think after changing the version, we can only test it once this `v10.2.0` is deployed.
As I am getting this error
```
Couldn't find any versions for "taskcluster-lib-app" that matches "10.2.0"
? Please choose a version of "taskcluster-lib-app" from this list:
```
on running `yarn`.
Should I wait for this version to deploy? Also is it possible to add me to the mailing list when this is getting deployed, so I will get notified about the release

**Comment by djmitche** [comment]
Ah, sorry, Travis failed to upload the new version:
  https://travis-ci.org/taskcluster/taskcluster-lib-app/jobs/465469382
I'll do it manually.

**Comment by djmitche** [comment]
fixed - sorry about that!

**Pull request merged**
