### PR TITLE
Bug 1412005: add robots.txt and sitemap.xml

### PR DESCRIPTION
**Pull request by djmitche**
The robots.txt bit is pretty obvious here, but I'm less confident about the sitemap.  My reason to add it is, ZAP wants me to, but we could also ask that Simon configure ZAP not to scan this for APIs.

I'm not sure what URL we would expose for a sitemap..

### CODE REVIEW

**Review by imbstack — APPROVED** [review]
I definitely think the robots.txt is fine. I agree the sitemap stuff is a bit confusing. Maybe ask the team why they scan it and

1) if they can remove it from the scan or
2) what we should be putting there if they do need to scan it

I feel like an empty xml document is probably considered cheating in this context? :p

**Comment by djmitche** [comment]
@psiinon ^^ what do you think?

**Comment by psiinon** [comment]
Sorry for the delayed response.
We always looks for robots.txt and sites.xml as these can help us spider the site.
Serving up a fake sites.xml file for ZAP seems a bit wrong, we could easily report the same vulnerabilities on any other 404.
So I'd recommend either adding the right headers to all 404s or if thats too much trouble then we can filter out some of the warnings on those pages. However I'm wary of ignoring all alerts on all 404s as we have seen real XSSs on 404s before (The page <script>alert(1);</script> you were looking for doenst exist) ;)

**Comment by djmitche** [comment]
OK, I'll leave the sitemap as a 404.  I think the headers should be present on the 404's anyway.

**Comment by djmitche** [comment]
(I just removed the second, sitemap-related commit from the PR)

**Comment by djmitche** [comment]
v2.1.0

**Pull request merged**
